import localFont from "next/font/local";
import "./globals.css";
import AuthButton from "@/components/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-6 bg-black text-white`}
      >
        <div className="">
          <header className="flex border-b border-b-foreground/10 justify-right mb-5 h-24 justify-items-end justify-end space-x-4">
            <AuthButton />
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
